Repository LearningBay24/LearningBay24-backend, pull requests merged in 2022-05, with the labels that each got.

#27 add file package
  config/config.go
  db/file.go
  example.config.toml
Labels: draft-pr

#39 Course material
  course/course.go
  courseMaterial/courseMaterial.go
Labels: basic-functionality

#43 Database migrations
  .build.yml
  .gitignore
  README.md
  api/api.go
  config/config.go
  contrib/docker-test-database/docker-compose.yml
  contrib/docker-test-database/mariadb-data/learningbay24-dummy-init.sql
  courseMaterial/courseMaterial.go
  dbconfig.yml
  dbi/dummy.go
  dbi/file.go
  dbi/user.go
  example.config.toml
  go.mod
  go.sum
  main.go
  migrations/20220510114608-initial.sql
  migrations/20220510123901-field_of_study_semesters_as_int.sql
  migrations/20220510173806-user_email_unique.sql
  models/appointment.go
  models/appointment_test.go
  models/boil_main_test.go
  models/boil_queries_test.go
  models/boil_suites_test.go
  models/certificate_test.go
  models/course_has_files_test.go
  models/course_test.go
  models/directory_test.go
  models/exam.go
  models/exam_test.go
  models/field_of_study.go
  models/field_of_study_has_course_test.go
  models/field_of_study_test.go
  models/file_test.go
  models/forum_entry_test.go
  models/forum_test.go
  models/graduation_level_test.go
  models/language_test.go
  models/mysql_main_test.go
  models/mysql_suites_test.go
  models/notification_test.go
  models/role_test.go
  models/submission_test.go
  models/user.go
  models/user_has_course_test.go
  models/user_has_exam_test.go
  models/user_submission_test.go
  models/user_test.go
  sqlboiler.toml
Labels: documentation, enhancement

#53 Materials api
  api/api.go
  courseMaterial/courseMaterial.go
  dbi/file.go
  example.config.toml
  main.go
Labels: basic-functionality, priority
