Repository LearningBay24/LearningBay24-backend, pull requests merged in 2022-06, with the labels that each got.

#49 User: Funktionen `Delete` und `GetById`
  api/api.go
  dbi/dummy.go
  dbi/user.go
  main.go
Labels: C-basic-functionality, A-User, P-high, S-watiting-on-review

#61 Cookies
  api/api.go
  main.go
  migrations/20220603170646-standard_roles.sql
Labels: C-basic-functionality, P-critical, A-Cookie, S-watiting-on-review

#85 Submission
  api/api.go
  course/submission.go
  main.go
Labels: C-basic-functionality, P-critical, S-waiting-on-author, A-Abgabe

#29 Calender
  api/api.go
  calender/calender.go
  calender/calender_test.go
  go.mod
  go.sum
  main.go
  migrations/20220610161111-add_appointment_duration.sql
  models/appointment.go
  models/boil_queries.go
  models/boil_table_names.go
  models/boil_types.go
  models/boil_view_names.go
  models/certificate.go
  models/course.go
  models/course_has_files.go
  models/directory.go
  models/exam.go
  models/field_of_study.go
  models/field_of_study_has_course.go
  models/file.go
  models/forum.go
  models/forum_entry.go
  models/graduation_level.go
  models/language.go
  models/mysql_upsert.go
  models/notification.go
  models/role.go
  models/submission.go
  models/user.go
  models/user_has_course.go
  models/user_has_exam.go
  models/user_submission.go
Labels: C-basic-functionality, A-Kalender, P-critical, S-waiting-on-author

#90 Max upload limit
  api/api.go
  config/config.go
  course/submission.go
  courseMaterial/courseMaterial.go
  dbi/file.go
  exam/exam.go
  example.config.toml
  main.go
  migrations/20220621195849-user_file_upload_size.sql
  models/field_of_study.go
  models/user.go
Labels: A-Testing, P-critical, A-Upload, A-Server, S-watiting-on-review

#105 Use Middleware to make id's available
  api/api.go
  main.go
Labels: C-enhancement, A-User, A-Testing, P-critical, A-Cookie, A-Autorisierung

#115 Add API for deleting file from course
  api/api.go
  main.go
Labels: C-basic-functionality, A-Kurs, P-critical, A-Upload

#127 Restructure error handling for proper status codes
  api/api.go
  errs/errs.go
Labels: C-enhancement, A-Testing, P-critical

#130 Don't allow creator registering for own exam
  api/api.go
  errs/errs.go
  exam/exam.go
Labels: C-bug, A-Kurs, P-critical, S-watiting-on-review

#132 Add custom errors
  api/api.go
  calender/calender.go
  course/course.go
  course/submission.go
  courseMaterial/courseMaterial.go
  dbi/file.go
  dbi/user.go
  errs/errs.go
  exam/exam.go
Labels: C-enhancement, P-critical

#133 Course fix
  api/api.go
  calender/calender.go
  course/course.go
  main.go
Labels: C-basic-functionality, A-Kurs, P-critical

#128 Implement `GetUserCourseRole` endpoint
  api/api.go
  main.go
Labels: C-enhancement, A-User, A-Kurs, P-critical, S-watiting-on-review

#137 Calender authorization
  api/api.go
  main.go
Labels: C-basic-functionality, A-Kalender, P-critical

#140 Exam deregister fix
  api/api.go
  exam/exam.go
Labels: P-critical, A-Klausur

#113 Submissions fixes
  api/api.go
  course/submission.go
  main.go
Labels: P-critical, S-Blocked, A-Abgabe
